---
title: "SMAC lactate prognostic value"
author: "James Watson"
date: "2025-01-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = T, cache.comments = FALSE,
                      echo = F, include = TRUE, 
                      fig.width = 8, fig.height = 8,
                      fig.pos = 'H',dev = 'png', dpi = 300)

library(tidyverse)
# library(mgcv)
library(brms)
library(ggplot2)
library(gridExtra)
# library(lme4)

binomial_smooth <- function(...) {
  geom_smooth(method = "gam", method.args = list(family = "binomial"), ...)
}
```




plotting params

```{r}
sqrt_breaks = c(1,4,9,16,25,36,50,64,81)
breaks <- 10^(-10:10)
minor_breaks <- rep(1:9, 21)*(10^rep(-10:10, each=9))

SEsmooth=F
my_alpha=0.2
bun_limits = c(1,100)
crea_limits = c(10,1000)

mortality_threshold = 0.05
```

## Training data

We fit a prognostic model to the lactate data and then test how well it performs in terms of predictive performance on a large external dataset (SMAC).


```{r load_data}
sm_data = readr::read_csv(file = 'Data/Analysis_data.csv')

sm_data_analysis = sm_data %>% 
  filter(INCLUDE_CC_ANALYSIS,
         !is.na(Hb), Lactate<20, !is.na(Lactate)) %>%
  mutate(Anaemic=ifelse(Hb<5,'Yes','No'),
         Anaemic=as.factor(Anaemic),
         Coma = ifelse(Coma_Final==1,'Yes','No'))


aggregate(Died~STUDY, data = sm_data_analysis, FUN = function(x) c(round(100*mean(x)), length(x)))

# cols = intersect(colnames(sm_data_analysis), colnames(smac))
# dat = rbind(sm_data_analysis[,cols], smac[,cols])
# table(dat$STUDY)
# dat$STUDY=as.factor(dat$STUDY)
# dat$SITEID=as.factor(dat$SITEID)
# dat$Age_cat=as.factor(dat$Age<5)
# dat$Anaemic= as.factor(dat$`Hb<5g/dL`)
```



## Prognostic models

histograms of data

```{r lactate_histogram, fig.width=10, fig.height=7}
sm_data_analysis %>% ggplot(aes(x=Lactate, group = Coma, colour = Coma))+
  geom_histogram()+theme_minimal()+facet_wrap(~Anaemic)+
  xlab("Lactate (mmol/L)")+ylab("Number of patients")
```



individual studies

```{r individ_studies}
sm_data_analysis %>% filter(Lactate<20) %>%
  group_by(STUDY) %>%
  mutate(STUDY = paste0(STUDY, " (n = ", n(), ")")) %>%
  ggplot(aes(x=Lactate, y = Died_28D))+
  geom_point(pch='.')+theme_minimal()+
  geom_hline(yintercept = mortality_threshold)+ylab('Proportion dead by day 28')+
  xlab('Lactate (umol/L)')+ 
  geom_smooth(method='gam',method.args = list(family='binomial'))+
  facet_wrap(~STUDY)
```


simple logistic regression

```{r}
mod_lactate = lme4::glmer(Died_28D ~ (Lactate>5) + Anaemic + Coma_Final + (1|STUDY/SITEID), family = 'binomial', data = sm_data_analysis)
summary(mod_lactate)
```



brms 

```{r lactate_model_fit, fig.width=10, fig.height=7}
## mgcv version
sm_data_analysis$STUDY=as.factor(sm_data_analysis$STUDY)
sm_data_analysis$SITEID=as.factor(sm_data_analysis$SITEID)
gam_lactate = mgcv::gam(Died ~ s(Lactate, by=interaction(Anaemic,Coma_Final),k=4) + Anaemic + Coma_Final + s(SITEID, bs='re') + s(sqrt(Age)),
          data = sm_data_analysis, family = binomial())

gam_lactate_2 = mgcv::gam(Died ~ s(Lactate, by=interaction(Anaemic,Coma_Final), k=3) + Anaemic + Coma_Final + s(SITEID, bs='re') + s(sqrt(Age)),
          data = sm_data_analysis, family = binomial())


# m2_lactate = brm(bf(Died ~ s(Lactate, by=Anaemic,k=4)+Anaemic+Coma_Final+(1|STUDY/SITEID)),
#           data = sm_data_analysis , 
#           family = bernoulli(), cores = 4, seed = 17,
#           iter = 4000, warmup = 2000, thin = 10, refresh = 250)
sm_data_analysis$M0_preds=predict(gam_lactate,exclude = "s(SITEID)",type = 'response')
sm_data_analysis$M1_preds=predict(gam_lactate_2,exclude = "s(SITEID)",type = 'response')

p1=sm_data_analysis %>% 
    ggplot(aes(x=Lactate, y = M0_preds, group = interaction(Anaemic,Coma_Final), linetype = Coma, colour = Anaemic))+geom_line()+theme_minimal()+xlab("Lactate (mmol/L)")+ylab("Predicted probability of death")+
  ggtitle('k=5')+geom_hline(yintercept = mortality_threshold)+geom_vline(xintercept = 7)
p2=sm_data_analysis %>% 
    ggplot(aes(x=Lactate, y = M1_preds, group = interaction(Anaemic,Coma_Final), linetype = Coma, colour = Anaemic))+  geom_line()+theme_minimal()+xlab("Lactate (mmol/L)")+ylab("Predicted probability of death")+
    ggtitle('k=3')+geom_hline(yintercept = mortality_threshold)+geom_vline(xintercept = 7)

grid.arrange(p1,p2,nrow=1)
```

## testing data - SMAC

```{r load_smac}
smac = read_csv('Data/smac.csv')
table(hb=is.na(smac$HB), hct=is.na(smac$HCT))
smac = smac %>%
  mutate(Reason_exclude = case_when(
    is.na(LACTATE) ~ 'No lactate measurement',
    is.na(HB) ~ 'No haemoglobin or haematocrit',
    is.na(Died) ~ 'No outcome',
    is.na(AGE) ~ 'No age',
    T ~ 'INCLUDE'))
table(smac$Reason_exclude)
smac = smac %>% filter(Reason_exclude =='INCLUDE') %>%
  mutate(Lactate=LACTATE, Anaemic=ifelse(HB<5,'Yes','No'), Hb=HB)
```


```{r lactate_histogram_smac, fig.width=10, fig.height=7}
smac %>% ggplot(aes(x=Lactate, group = Coma_Final, colour = Coma_Final))+
  geom_histogram()+theme_minimal()+facet_wrap(~Anaemic)+
  xlab("Lactate (mmol/L)")+ylab("Number of patients")
```

```{r}
k_bins_calibration=10
```



```{r calibration_plot_model0}
smac$pred_mod_gam0 = predict(gam_lactate,exclude = "s(STUDY)",type = 'response',newdata = smac)
quantiles_mortality_pred0 = quantile(smac$pred_mod_gam0, probs = seq(0,1,length.out=k_bins_calibration+1))

#cut(pred_mod_gam, breaks=seq(0,1,by=.05))
smac = smac %>% mutate(pred_bin = cut(pred_mod_gam0, quantiles_mortality_pred0)) 
smac_calibration1 = smac %>%
  group_by(pred_bin, Anaemic) %>%
  mutate(predicted_mortality = mean(pred_mod_gam0),
         observed_mortality = mean(Died),
         N_bin = n(),
         alpha1 = sum(Died),
         beta1 = N_bin-sum(Died),
         upper_mort = qbeta(.975,1+alpha1,1+beta1),
         lower_mort = qbeta(.025,1+alpha1,1+beta1)) %>%
  distinct(pred_bin, Anaemic, .keep_all = T) %>% filter(N_bin>10) %>%
  select(predicted_mortality,observed_mortality,N_bin,Anaemic,lower_mort, upper_mort,pred_bin) %>%
  arrange(predicted_mortality, Anaemic)
c1=smac_calibration1 %>% ggplot(aes(x = predicted_mortality, y=observed_mortality, group = Anaemic, colour = Anaemic))+
  geom_point()+ scale_x_log10()+scale_y_log10()+
  # xlim(0,.55)+ylim(0,.55)+
  theme_minimal()+geom_abline(slope = 1,intercept = 0)+
  geom_errorbar(aes(ymin = lower_mort, ymax = upper_mort), width = 0.02) +
  xlab("Predicted mortality")+ylab("Observed mortality")+
  geom_hline(yintercept = mortality_threshold)+geom_vline(xintercept = mortality_threshold)+
  ggtitle('k=5')
```


```{r calibration_plot_model1}
smac$pred_mod_gam1 = predict(gam_lactate_2,exclude = "s(STUDY)",type = 'response',newdata = smac)
quantiles_mortality_pred1 = quantile(smac$pred_mod_gam1, probs = seq(0,1,length.out=k_bins_calibration+1))

#cut(pred_mod_gam, breaks=seq(0,1,by=.05))
smac = smac %>% mutate(pred_bin = cut(pred_mod_gam1, quantiles_mortality_pred1)) 
smac_calibration2 = smac %>%
  group_by(pred_bin, Anaemic) %>%
  mutate(predicted_mortality = mean(pred_mod_gam1),
         observed_mortality = mean(Died),
         N_bin = n(),
         alpha1 = sum(Died),
         beta1 = N_bin-sum(Died),
         upper_mort = qbeta(.975,1+alpha1,1+beta1),
         lower_mort = qbeta(.025,1+alpha1,1+beta1)) %>%
  distinct(pred_bin, Anaemic, .keep_all = T) %>% filter(N_bin>10) %>%
  select(predicted_mortality,observed_mortality,N_bin,Anaemic,lower_mort, upper_mort,pred_bin) %>%
  arrange(predicted_mortality, Anaemic)
c2=smac_calibration2 %>% ggplot(aes(x = predicted_mortality, y=observed_mortality, group = Anaemic, colour = Anaemic))+
  geom_point()+ scale_x_log10()+scale_y_log10()+
  # xlim(0,.55)+ylim(0,.55)+
  theme_minimal()+geom_abline(slope = 1,intercept = 0)+
  geom_errorbar(aes(ymin = lower_mort, ymax = upper_mort), width = 0.02) +
  xlab("Predicted mortality")+ylab("Observed mortality")+
  geom_hline(yintercept = mortality_threshold)+geom_vline(xintercept = mortality_threshold)+
   ggtitle('k=3')
```


```{r calibration, fig.width=10, fig.height=7}
grid.arrange(c1,c2,nrow=1)
```


```{r lactate_prognostic_models, fig.width=8, fig.height=8}
# h1=smac%>%
#   ggplot(aes(x=Lactate, color=`Hb<5g/dL`))+
#   geom_density()+theme_minimal()+
#   theme(axis.title.x = element_blank(), axis.text.x = element_blank(),  # Remove x-axis label
#         plot.margin = unit(c(0, 0.5, 0, 0.5), "cm"), legend.position = "none")+
#   coord_cartesian(xlim = c(0,13))+ggtitle(label = paste('SMAC (n=',nrow(smac),')',sep = ''))
# p1=smac%>%
#   ggplot(aes(x=Lactate,y=Died, color=`Hb<5g/dL`))+
#   binomial_smooth()+theme_minimal()+
#   theme(plot.margin = unit(c(0.5, 0.5, 0, 0.5), "cm"), legend.position = "none")+
#   ylab('Probability of death')+xlab('Lactate (mmol/L)')+
#   geom_hline(yintercept = mortality_threshold)+
#   coord_cartesian(ylim=c(0, .2), xlim = c(0,13))
# 
# h2=sm_data%>%
#   ggplot(aes(x=Lactate, color=`Hb<5g/dL`))+
#   geom_density()+theme_minimal()+
#   theme(axis.title.x = element_blank(), axis.text.x = element_blank(),  # Remove x-axis label
#         plot.margin = unit(c(0, 0.5, 0, 0.5), "cm"), legend.position = "none")+
#   coord_cartesian(xlim = c(0,13))+ggtitle(label = paste('Pooled severe malaria studies (n=',nrow(sm_data),')',sep = ''))
# 
# p2=sm_data%>%
#   ggplot(aes(x=Lactate,y=Died, color=`Hb<5g/dL`))+
#   binomial_smooth()+theme_minimal()+
#    theme(plot.margin = unit(c(0.5, 0.5, 0, 0.5), "cm"), legend.position = "none")+
#  ylab('Probability of death')+xlab('Lactate (mmol/L)')+
#   geom_hline(yintercept = mortality_threshold)+
#   coord_cartesian(ylim=c(0, .2), xlim = c(0,13))
# grid.arrange(h1, h2, p1,p2,nrow=2, ncol = 2, heights = c(1, 1.2))
# 
# 
# mod = gam(Died~ s(Lactate, by = as.numeric(Hb<5)) + s(STUDY, bs='re') + Coma_Final,
#           family = 'binomial',data = dat)
# summary(mod)
```




```{r lactate_prognostic_models_all, fig.width=8, fig.height=8}
# h1=dat%>%filter(Coma_Final==0)%>%
#   ggplot(aes(x=Lactate, color=`Hb<5g/dL`))+
#   geom_density()+theme_minimal()+
#   theme(axis.title.x = element_blank(), axis.text.x = element_blank(),  # Remove x-axis label
#         plot.margin = unit(c(0, 0.5, 0, 0.5), "cm"), legend.position = "none")+
#   coord_cartesian(xlim = c(0,13))+
#   ggtitle(label = paste('No coma (n=',sum(dat$Coma_Final==0,na.rm = T),')',sep = ''))
# p1=dat%>%filter(Coma_Final==0)%>%
#   ggplot(aes(x=Lactate,y=Died, color=`Hb<5g/dL`))+
#   binomial_smooth()+theme_minimal()+
#   theme(plot.margin = unit(c(0.5, 0.5, 0, 0.5), "cm"), legend.position = "none")+
#   ylab('Probability of death')+xlab('Lactate (mmol/L)')+
#   geom_hline(yintercept = mortality_threshold)+
#   coord_cartesian(ylim=c(0, .2), xlim = c(0,13))
# 
# h2=dat%>%filter(Coma_Final==1)%>%
#   ggplot(aes(x=Lactate, color=`Hb<5g/dL`))+
#   geom_density()+theme_minimal()+
#   theme(axis.title.x = element_blank(), axis.text.x = element_blank(),  # Remove x-axis label
#         plot.margin = unit(c(0, 0.5, 0, 0.5), "cm"), legend.position = "none")+
#   coord_cartesian(xlim = c(0,13))+
#   ggtitle(label = paste('Coma (n=',sum(dat$Coma_Final==1,na.rm = T),')',sep = ''))
# 
# p2=dat%>%filter(Coma_Final==1)%>%
#   ggplot(aes(x=Lactate,y=Died, color=`Hb<5g/dL`))+
#   binomial_smooth()+theme_minimal()+
#    theme(plot.margin = unit(c(0.5, 0.5, 0, 0.5), "cm"), legend.position = "none")+
#  ylab('Probability of death')+xlab('Lactate (mmol/L)')+
#   geom_hline(yintercept = mortality_threshold)+
#   coord_cartesian(ylim=c(0, .2), xlim = c(0,13))
# grid.arrange(h1, h2, p1,p2,nrow=2, ncol = 2, heights = c(1, 1.2))
```

