---
title: "Lactate"
author: "James Watson"
date: "2025-07-14"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = T, cache.comments = FALSE,
                      echo = F, include = TRUE, 
                      fig.width = 8, fig.height = 8,
                      fig.pos = 'H',dev = 'png', dpi = 300)


library(brms)
library(tidyverse)
library(grid)
library(gridExtra)
```



Plotting params

```{r}
source('setup_parameters.R')
```


## Load data

Analysis dataset
```{r}
load('RData/Analysis_dataset.RData')
```


Analysis of BUN data stratified by age group and coma status

```{r}
sm_data_lactate = sm_data_analysis %>% filter(!is.na(Lactate), !is.na(Hb)) %>%
  mutate(Hb_less_5 = as.numeric(Hb<5))
sm_data_lactate %>% ggplot(aes(x=Lactate, colour = Hb_less_5))+geom_density()+
  theme_bw()

f_brm_mod_lac = as.formula(bf(Died_28D ~ s(Lactate,by=Hb_less_5)+Coma+(1|STUDY/SITE_STUDY)))

f_path = 'RData/lactate_models.RData'
RUN_STAN_MODELS=F
if(!file.exists(f_path) | RUN_STAN_MODELS){
  mod_lactate_age_het = 
    brm(formula = f_brm_mod_lac,
        data = sm_data_lactate ,
        family = bernoulli(), cores = 4, seed = 858,
        iter = 2000, warmup = 1000, thin = 8, refresh = 250)
  
  # mod_bun_age_het2 = 
  #   brm(formula = f_brm_mod_bun,
  #       data = sm_data_bun %>% filter(STUDY!='TRACT'),
  #       family = bernoulli(), cores = 4, seed = 17,
  #       iter = 2000, warmup = 1000, thin = 1, refresh = 250)
  # 
  # mod_bun_age_het3 = 
  #   brm(formula = f_brm_mod_bun,
  #       data = sm_data_bun %>% filter(PfHRP2_ng_ml > 800),
  #       family = bernoulli(), cores = 4, seed = 17,
  #       iter = 2000, warmup = 1000, thin = 1, refresh = 250)

  save(mod_lactate_age_het,
       # mod_bun_age_het2,mod_bun_age_het3,
       file = f_path)
} else {
  load(f_path)
}
```



```{r}
k_vals=40
test_data = expand_grid(Lactate = seq(0, 15,length.out=k_vals),
                        Age_category=unique(sm_data_lactate$Age_category),
                        Hb_less_5=0:1,
                        Coma=unique(sm_data_lactate$Coma),
                        STUDY=unique(sm_data_lactate$STUDY), 
                        SITE_STUDY = -1) %>% 
  arrange(Lactate)

# get model predictions
# Full model
preds = posterior_epred(mod_lactate_age_het, newdata = test_data, re_formula = NA)
test_data$pred_mod_lactate_age_het = colMeans(preds)
test_data$lactate_age_het_threshold = apply(preds, 2, f_threshold,mortality_threshold=mortality_threshold)

# # Remove TRACT
# preds = posterior_epred(mod_bun_age_het2, newdata = test_data, re_formula = NA)
# test_data$pred_mod_bun_age_het2 = colMeans(preds)
# test_data$bun_age_het_threshold2 = apply(preds, 2, f_threshold,mortality_threshold=mortality_threshold)
# 
# 
# # High HRP2 model
# test_data3 = test_data %>% filter(Age_category !='>15') %>% mutate(Age_category = droplevels(Age_category))
# preds = posterior_epred(mod_bun_age_het3, newdata = test_data3, re_formula = NA)
# test_data3$pred_mod_bun_age_het3 = colMeans(preds)
# test_data3$bun_age_het_threshold3 = apply(preds, 2, f_threshold,mortality_threshold=mortality_threshold)
```



```{r age_vs_BUN, fig.width=8, fig.height=8}
p1=test_data %>% filter(Coma=='No') %>%
  mutate(Hb_less_5 = as.factor(Hb_less_5)) %>%
  ggplot(aes(x = Lactate, y = pred_mod_lactate_age_het, 
             linetype = Hb_less_5,
             group = Hb_less_5))+
  geom_line()+ ylab('Predicted mortality')+
  theme_bw(base_size = 13)+
  xlab('Lactate (mmol/L)')+
  geom_hline(yintercept = mortality_threshold)+
labs(colour='Age category')+
  theme(legend.position = c(0.02, 0.98),  # (x, y) in [0,1] relative to plot area
        legend.justification = c(0, 1))   # align legend's bottom-left to that point
p1_threshold=test_data %>%
  ggplot(aes(x = Lactate, y = lact, 
             colour = Age_category,linetype = Coma,
             group = interaction(Age_category,Coma)))+
  geom_line()+ylab('Probability mortality > 5%')+
  scale_x_log10() + theme_bw(base_size = 13)+
  annotation_logticks(sides='b')+
  xlab('Urea Nitrogen (mmol/L)')+
  geom_hline(yintercept = .9)+geom_vline(xintercept = 10)+
  theme(legend.position = 'none')
grid.arrange(p1, p1_threshold)
```


```{r age_vs_BUN_remove_TRACT, fig.width=10, fig.height=7}
p1=test_data %>%
  ggplot(aes(x = BUN, y = pred_mod_bun_age_het2, 
             colour = Age_category,linetype = Coma,
             group = interaction(Age_category,Coma)))+
  geom_line()+ ylab('Predicted mortality')+
  scale_x_log10() +
  annotation_logticks(sides='b')+theme_bw(base_size = 13)+
  xlab('Urea Nitrogen (mmol/L)')+
  geom_hline(yintercept = mortality_threshold)
p1_threshold=test_data %>%
  ggplot(aes(x = BUN, y = bun_age_het_threshold2, 
             colour = Age_category,linetype = Coma,
             group = interaction(Age_category,Coma)))+
  geom_line()+ylab('Probability mortality > 5%')+
  scale_x_log10() + theme_bw(base_size = 13)+
  annotation_logticks(sides='b')+
  xlab('Urea Nitrogen (mmol/L)')+
  geom_hline(yintercept = .95)+geom_vline(xintercept = 10)
grid.arrange(p1, p1_threshold)
```


```{r age_vs_BUN_high_hrp2, fig.width=10, fig.height=7}
p1=test_data3 %>%
  ggplot(aes(x = BUN, y = pred_mod_bun_age_het3, 
             colour =Age_category,linetype = Coma,
             group = interaction(Age_category,Coma)))+
  geom_line()+ ylab('Predicted mortality')+
  scale_x_log10() +
  annotation_logticks(sides='b')+theme_bw(base_size = 13)+
  xlab('Urea Nitrogen (mmol/L)')+
  geom_hline(yintercept = mortality_threshold)
p1_threshold=test_data3 %>%
  ggplot(aes(x = BUN, y = bun_age_het_threshold3, 
             colour = Age_category,linetype = Coma,
             group = interaction(Age_category,Coma)))+
  geom_line()+ylab('Probability mortality > 5%')+
  scale_x_log10() + theme_bw(base_size = 13)+
  annotation_logticks(sides='b')+
  xlab('Urea Nitrogen (mmol/L)')+
  geom_hline(yintercept = .95)+geom_vline(xintercept = 10)
grid.arrange(p1, p1_threshold)
```
