---
title: "Analysis dataset"
author: "James Watson"
date: "2025-07-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = T, cache.comments = FALSE,
                      echo = F, include = TRUE, 
                      fig.width = 8, fig.height = 8,
                      fig.pos = 'H',dev = 'png', dpi = 300)
library(zscorer)
library(tidyverse)
```


```{r}
# convert SDTM into an analysis format
# source('make_adam.R')
```



```{r render_descriptive_prep, echo=F}
# rmarkdown::render('descriptive_analysis_prep.Rmd')
```


## Make analysis dataset

Load data

```{r}
sm_data = readr::read_csv('Data/adam_out.csv')

sm_data = sm_data%>% arrange(STUDY) %>% 
  mutate(Died_28D = ifelse(`Died within 28 days`=='Yes',1,0))
```

```{r make_analysis_data}
#Remove AQ Gambia from analysis data-set as unreliable creatinine values
sm_data = sm_data %>% 
  mutate(INCLUDE_CC_ANALYSIS = !(
    (is.na(Weight_kg) & is.na(Age) & is.na(Height_cm)) | # age, weight and height all missing
      is.na(Malaria_Positive) | # no malaria confirmation
      is.na(Died) | # no outcome
      (is.na(Creatinine_umol_L) & is.na(BUN)) | # no creatinine or bun
      is.na(Coma) | # no coma status
      !Malaria_Positive |
      STUDY=='AQ Gambia'),
    
    INCLUDE_CC_ANALYSIS_SENSITIVITY = # just core variables, don't exclude based on malaria confirmation or the AQ Gambia study
      !(is.na(Weight_kg) |is.na(Age)) & # both age and weight missing
      !is.na(Died) & # no outcome
      (!is.na(Creatinine_umol_L) | !is.na(BUN)) & # no creatinine or bun
      !is.na(Coma) )

table(sm_data$INCLUDE_CC_ANALYSIS,useNA = 'ifany')

table(sm_data$STUDY, sm_data$INCLUDE_CC_ANALYSIS)
table(sm_data$STUDY, sm_data$Malaria_Positive,useNA = 'ifany')

print(aggregate(Age ~ STUDY+INCLUDE_CC_ANALYSIS, data = sm_data, FUN = quantile))
# print(aggregate(RFSTDTC ~ STUDY, data = sm_data, FUN = function(x) range(x,na.rm = T)))
print(aggregate(Died ~ STUDY, data = sm_data, FUN = function(x) round(100*mean(x),1)))
```



Analysis data

```{r analysis_data}
xx = sm_data %>% filter(INCLUDE_CC_ANALYSIS)
writeLines(sprintf('Analysis data: there are %s patients from %s studies with at least one baseline creatinine or BUN measurement. %s patients have creatinine; %s patients have BUN; %s patients have both.',
                   nrow(xx),
                   length(unique(xx$STUDYID)),
                   sum(!is.na(xx$Creatinine_umol_L)),
                   sum(!is.na(xx$BUN)),
                   sum(!is.na(xx$Creatinine_umol_L) & !is.na(xx$BUN))
))
```

reasons for exclusion

```{r}
sm_data = sm_data %>%
  mutate(Reason_exclude = case_when(
    INCLUDE_CC_ANALYSIS ~ NA,
    !INCLUDE_CC_ANALYSIS & STUDY=='AQ Gambia' ~ 'AQ Gambia study',
    !INCLUDE_CC_ANALYSIS & is.na(Creatinine_umol_L) & is.na(BUN) ~ 'No BUN or Creatinine measurement',
    !INCLUDE_CC_ANALYSIS & (is.na(Malaria_Positive) | !Malaria_Positive) ~ 'No confirmed malaria',
    !INCLUDE_CC_ANALYSIS & is.na(Died) ~ 'No mortality outcome',
    !INCLUDE_CC_ANALYSIS & is.na(Weight_kg) & is.na(Age) ~ 'No weight/age',
    !INCLUDE_CC_ANALYSIS & is.na(Coma) ~ 'No coma information',
    T ~ 'weird!'
  ))
table(sm_data$Reason_exclude, sm_data$INCLUDE_CC_ANALYSIS, useNA = 'ifany')

table(sm_data$Reason_exclude)

table(sm_data$STUDY,sm_data$Reason_exclude)
```



## Single imputation of weight, height and age

Missing data in analysis dataset

```{r}
sum(sm_data$INCLUDE_CC_ANALYSIS)

n_creat = sum(sm_data$INCLUDE_CC_ANALYSIS & !is.na(sm_data$Creatinine_umol_L))

writeLines(sprintf('In the analysis dataset, Age is missing in %s patients', sum(is.na(sm_data$Age) & sm_data$INCLUDE_CC_ANALYSIS)))
writeLines(sprintf('In the creatinine analysis dataset, Age is missing in %s patients', sum(is.na(sm_data$Age) & sm_data$INCLUDE_CC_ANALYSIS & !is.na(sm_data$Creatinine_umol_L))))

writeLines(sprintf('In the analysis dataset, Weight is missing in %s patients', sum(is.na(sm_data$Weight_kg) & sm_data$INCLUDE_CC_ANALYSIS)))
n_miss_weight = sum(is.na(sm_data$Weight_kg) & sm_data$INCLUDE_CC_ANALYSIS & !is.na(sm_data$Creatinine_umol_L))
writeLines(sprintf('In the creatinine analysis dataset, Weight is missing in %s patients (%s%%)', n_miss_weight, round(100*n_miss_weight/n_creat)))

writeLines(sprintf('In the analysis dataset, Height is missing in %s patients', sum(is.na(sm_data$Height_cm) & sm_data$INCLUDE_CC_ANALYSIS)))
n_miss_height = sum(is.na(sm_data$Height_cm) & sm_data$INCLUDE_CC_ANALYSIS & !is.na(sm_data$Creatinine_umol_L))
writeLines(sprintf('In the creatinine analysis dataset, Height is missing in %s patients (%s%%)', n_miss_height,round(100* n_miss_height/n_creat)))
```

```{r multiple_imputation}
RUN_IMPUTE_MODEL = F
source('multiple_imputation.R')
detach("package:mice", unload=TRUE)
```


## Make analysis data

```{r}
imp1 = mice::complete(imp_list,action = 1)
sm_data$Weight_imputed = imp1$Weight_kg
sm_data$Age_imputed = imp1$Age
sm_data$Height_imputed = imp1$Height_cm
sm_data$MUAC_imputed = imp1$`Mid-Upper Arm Circumference_cm`

sm_data$log10_BUN_imputed = imp1$log10_BUN
sm_data$log10_Creatinine_imputed = imp1$log10_Creatinine
sm_data$Lactate_imputed = imp1$Lactate
sm_data$Bicarbonate_imputed = imp1$Bicarbonate_mEq_L

# select datasets with analysis pop from imputed data
imp_data = list()
for(i in 1:imp_list$m){
  xx = mice::complete(imp_list, action = i)
  xx = xx[sm_data$INCLUDE_CC_ANALYSIS, ]
  imp_data[[i]] = xx
}
rm(imp_list)

save(imp_data, file = 'RData/imputed_analysis_datasets.RData')
```

compute weight for age z-scores

```{r weight_for_age_zscores}
sm_data = sm_data  %>%
  mutate(sex = ifelse(SEX=='M',1,2),
         age_days = ifelse(Age_imputed<10, Age_imputed*365, NA))
sm_data =
  addWGSR(data = sm_data, sex = 'sex', 
          firstPart = 'Weight_imputed', 
          secondPart = 'age_days',index = 'wfa')

sm_data$wfaz = ifelse(sm_data$wfaz>5 | sm_data$wfaz< -6, NA, sm_data$wfaz)
sm_data %>% dplyr::filter(!is.na(wfaz)) %>% 
  ggplot(aes(x= Age, y = wfaz, color=SEX))+geom_point()+geom_hline(yintercept = 0) +
  theme_minimal() + xlab('Age (years)')+ylab('Weight for age z-score')+
  geom_smooth(aes(group=NA))+
  facet_wrap(~STUDY)
```



Final analysis datasets

```{r}
sm_data_analysis = sm_data %>% 
  filter(INCLUDE_CC_ANALYSIS) %>%
  mutate(Coma = ifelse(Coma==1,'Yes','No'),
         Weight_category = cut(Weight_imputed, breaks = c(0,30,100), labels = c(">30","≤30"),include.lowest=T),
         Age_category = cut(Age_imputed, breaks = c(0,2,5,15,100), labels = c("≤2","(2,5]","(5,15]",">15")))

sm_data_analysis = sm_data_analysis %>%
  mutate(
    Coma = as.factor(Coma),
    COUNTRY=as.factor(COUNTRY),
    SITE_STUDY=paste(SITEID, STUDY,sep = '_'),
    SITE_STUDY = as.factor(SITE_STUDY),
    BUN_ANALYSIS = !is.na(BUN),
    CREAT_ANALYSIS = !is.na(Creatinine_umol_L),
    BUN_CREAT_ANALYSIS = BUN_ANALYSIS & CREAT_ANALYSIS)

#we use single imputation for weight and height
writeLines(sprintf('Height is missing in %s, weight is missing in %s', sum(is.na(sm_data_analysis$Height_cm)),
                   sum(is.na(sm_data_analysis$Weight_kg))))
table(sm_data_analysis$STUDY, is.na(sm_data_analysis$Height_cm))
sm_data_analysis = sm_data_analysis %>%
  mutate(Age = ifelse(is.na(Age), Age_imputed, Age),
         Weight_kg = ifelse(is.na(Weight_kg), Weight_imputed, Weight_kg),
         Height_cm = ifelse(is.na(Height_cm), Height_imputed, Height_cm),
         year_admission = ifelse(is.na(year_admission)&(STUDYID=='CCFRW'),1994,year_admission))
```



```{r}
save(sm_data_analysis, sm_data, file = 'RData/Analysis_dataset.RData')
save(sm_data, file = 'RData/All_data_Severe_malaria.RData')
```

