---
title: "Renal Analysis Severe Malaria"
author: "James Watson"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = T, cache.comments = FALSE,
                      echo = F, include = TRUE, 
                      fig.width = 8, fig.height = 8,
                      fig.pos = 'H',dev = 'png', dpi = 300)

library(mgcv)
library(tidyverse)
library(grid)
library(gridExtra)
library(gtools)
library(broom)
```



Plotting params

```{r}
source('setup_parameters.R')
```


## Load data

Analysis dataset
```{r}
load('RData/Analysis_dataset.RData')

sm_data_analysis = sm_data_analysis %>%
  mutate(Age_Categories3 = cut(Age,breaks=c(0,5,15,100)),
         Age_Categories3 = fct_recode(
           Age_Categories3,
           "<5"     = "(0,5]",
           "[5,15]" = "(5,15]",
           ">15"    = "(15,100]"
         ))

print(aggregate(Age ~ STUDY, data = sm_data_analysis, FUN = quantile))
print(aggregate(Died ~ STUDY, data = sm_data_analysis, FUN = function(x) round(100*mean(x),1)))


writeLines(sprintf('There are %s patients in the whole dataset. Of these %s patients are in the analysis dataset. %s patients have creatinine measured; %s patients have BUN measured; %s patients have both measured.',
                   nrow(sm_data),
                   nrow(sm_data_analysis),
                   sum(!is.na(sm_data_analysis$Creatinine_umol_L)),
                   sum(!is.na(sm_data_analysis$BUN)),
                   sum(!is.na(sm_data_analysis$Creatinine_umol_L) & !is.na(sm_data_analysis$BUN))
))

writeLines(sprintf('n=%s patients are < than 15 years of age',
                   sum(sm_data_analysis$Age<15)))
writeLines(sprintf('n=%s patients are from Africa',
                   sum(sm_data_analysis$Continent=='AFRICA')))
writeLines(sprintf('n=%s patients died with 28 days (%s%%)',
                   sum(sm_data_analysis$Died),
                   round(100*mean(sm_data_analysis$Died),1)))

summary_table <- sm_data_analysis %>%
  group_by(STUDY) %>%
  summarise(
    Years = paste(c(min(lubridate::year(date_admission)), max(lubridate::year(date_admission))), collapse = "-"),
    N_patients = n(),
    Countries = paste(unique(COUNTRY), collapse = ", "),
    Age_summary = {
      a <- Age[!is.na(Age)]
      sprintf("%.1f [%.1f–%.1f]", round(median(a)), round(quantile(a, 0.25)), round(quantile(a, 0.75)))
    },
    Mortality = round(100*mean(Died),1),
    `Creatinine measured`=sum(!is.na(Creatinine_umol_L)),
    `BUN measured` = sum(!is.na(BUN)),
    `Lactate measured` = sum(!is.na(Lactate))
  )
summary_table

latex_code=knitr::kable(summary_table, format = "latex", booktabs = TRUE,
                        caption = "Summary of Patients by Study") 
writeLines(latex_code, "study_summary_table.tex")

```


```{r BUN_Creatinine_ratio}
sm_both = sm_data_analysis %>% filter(!is.na(BUN), !is.na(Creatinine_umol_L))
sm_both %>% ggplot(aes(x=BUN, y=Creatinine_umol_L, colour = STUDY))+
  geom_point()+ scale_x_log10(breaks = breaks, minor_breaks = minor_breaks)+
  scale_y_log10(breaks = breaks, minor_breaks = minor_breaks)+theme_bw()+
  ylab('Creatinine (umol/L)')+xlab('Blood urea nitrogen (mmol/L)')

sm_both %>% ggplot(aes(x=BUN, y=Creatinine_umol_L/BUN, colour = STUDY))+
  geom_point()+ scale_x_log10(breaks = breaks, minor_breaks = minor_breaks)+
  scale_y_log10(breaks = breaks, minor_breaks = minor_breaks)+theme_bw()+
  xlab('Blood urea nitrogen (mmol/L)')+ylab('Creatinine/urea ratio')+
  geom_smooth(aes(group=NA))


sm_both %>% 
  ggplot(aes(x=Weight_kg, y=Creatinine_umol_L/BUN, colour = STUDY))+
  geom_point()+
  scale_y_log10(breaks = breaks, minor_breaks = minor_breaks,limits=c(1,100))+
  theme_bw()+
  xlab('Weight (kg)')+ylab('Creatinine/urea ratio')+
  geom_smooth(aes(group=NA))
```


```{r creatinine_v_bun, fig.width=12, fig.height=8}
p1=sm_data_analysis %>% filter(!is.na(Creatinine_umol_L), !is.na(BUN)) %>%
  ggplot(aes(x=Creatinine_umol_L, y = BUN, colour = STUDY))+
  geom_point(alpha=0.5)+geom_smooth(se = F)+
  geom_hline(yintercept = 20)+geom_vline(xintercept = 265)+
  xlab('Creatinine (umol/L)')+ylab('BUN (mmol/L)')+
  scale_x_log10(breaks = breaks, minor_breaks = minor_breaks)+
  scale_y_log10(breaks = breaks, minor_breaks = minor_breaks)+
  annotation_logticks() + theme_bw(base_size = 20)+
  theme(
    legend.position = c(0.97, 0.03), 
    legend.justification = c(1, 0), 
    legend.background = element_rect(fill = "white", color = "black", size = 0.5),
    legend.margin = margin(6, 6, 6, 6),  
    legend.text = element_text(size = 9),
    legend.title = element_text(size = 10))


p2=sm_data_analysis %>% filter(!is.na(Creatinine_umol_L), !is.na(BUN)) %>%
  ggplot(aes(x=(Creatinine_umol_L/BUN), colour = STUDY))+
  geom_density()+theme_bw(base_size = 20)+
  scale_x_log10(breaks = breaks, minor_breaks = minor_breaks,limits=c(1,100))+
  annotation_logticks(sides='b')+
  xlab('Creatinine to BUN ratio')+ylab('')+
  scale_y_discrete(labels = NULL, breaks = NULL)+
  theme(legend.position = 'none')

grid.arrange(p1,p2,nrow=1)

p1=sm_data_analysis %>% filter(!is.na(Creatinine_umol_L), !is.na(BUN)) %>%
  ggplot(aes(x=Creatinine_umol_L, y = BUN, colour = Continent))+
  geom_point(alpha=0.5)+geom_smooth(se = F)+
  geom_hline(yintercept = 20)+geom_vline(xintercept = 265)+
  xlab('Creatinine (umol/L)')+ylab('BUN (mmol/L)')+
  scale_x_log10(breaks = breaks, minor_breaks = minor_breaks)+
  scale_y_log10(breaks = breaks, minor_breaks = minor_breaks)+
  annotation_logticks() + theme_bw(base_size = 20)+
  theme(
    legend.position = c(0.97, 0.03), 
    legend.justification = c(1, 0), 
    legend.background = element_rect(fill = "white", color = "black", size = 0.5),
    legend.margin = margin(6, 6, 6, 6),  
    legend.text = element_text(size = 9),
    legend.title = element_text(size = 10))
p2=sm_data_analysis %>% filter(!is.na(Creatinine_umol_L), !is.na(BUN)) %>%
  ggplot(aes(x=(Creatinine_umol_L/BUN), colour = Continent))+
  geom_density()+theme_bw(base_size = 20)+
  scale_x_log10(breaks = breaks, minor_breaks = minor_breaks,limits=c(1,100))+
  annotation_logticks(sides='b')+
  xlab('Creatinine to BUN ratio')+ylab('')+
  scale_y_discrete(labels = NULL, breaks = NULL)+
  theme(legend.position = 'none')
grid.arrange(p1,p2,nrow=1)

# Show differences by age
p1=sm_data_analysis %>% filter(!is.na(Creatinine_umol_L), !is.na(BUN)) %>%
  ggplot(aes(x=Creatinine_umol_L, y = BUN, colour = Age_Categories3))+
  geom_point(alpha=0.3)+geom_smooth(se = F)+
  geom_hline(yintercept = 20)+geom_vline(xintercept = 265)+
  xlab('Creatinine (umol/L)')+ylab('Urea nitrogen (mmol/L)')+
  scale_x_log10(breaks = breaks, minor_breaks = minor_breaks)+
  scale_y_log10(breaks = breaks, minor_breaks = minor_breaks)+
  annotation_logticks() + theme_bw(base_size = 20)+
    theme(
        legend.position = c(0.97, 0.03), 
        legend.justification = c(1, 0), 
        legend.background = element_rect(fill = "white", color = "black", size = .5),
        legend.margin = margin(6, 6, 6, 6),  
        legend.text = element_text(size = 20),
        legend.title = element_text(size = 20))+
    scale_colour_manual(
        name = "Age (years)",
        values = c("<5" = "orange", "[5,15]" = "darkred", ">15" = 'purple') 
    )

p2=sm_data_analysis %>% filter(!is.na(Creatinine_umol_L), !is.na(BUN)) %>%
  ggplot(aes(x=(Creatinine_umol_L/BUN), colour = Age_Categories3))+
  geom_density()+theme_bw(base_size = 20)+
  scale_x_log10(breaks = breaks, minor_breaks = minor_breaks,limits=c(1,100))+
  annotation_logticks(sides='b')+
  xlab('Creatinine to Urea nitrogen ratio')+ylab('')+
  scale_y_discrete(labels = NULL, breaks = NULL)+
  theme(legend.position = 'none')+
   scale_colour_manual(
        values = c("<5" = "orange", "[5,15]" = "darkred", ">15" = 'purple') 
    )

grid.arrange(p1,p2,nrow=1)

mod_bun_weight=lme4::lmer(log10(BUN) ~ Weight_kg + (1|STUDY), data = sm_data_analysis)
mod_creat_weight=lme4::lmer(log10(Creatinine_umol_L) ~ Weight_kg + (1|STUDY), data = sm_data_analysis)
summary(mod_bun_weight)
summary(mod_creat_weight)
10^(fixef(mod_bun_weight)['Weight_kg']*10)
10^(fixef(mod_creat_weight)['Weight_kg']*10)
```


```{r weight_age, fig.width=12, fig.height=12}
writeLines(sprintf('n=%s patients from %s studies have creatinine measured',sum(!is.na(sm_data_analysis$Creatinine_umol_L)), length(unique(sm_data_analysis$STUDY[!is.na(sm_data_analysis$Creatinine_umol_L)]))))

p1 = sm_data_analysis %>%filter(!is.na(Creatinine_umol_L))%>%
  ggplot(aes(x=Weight_kg, y = Creatinine_umol_L, colour = STUDY))+
  geom_jitter(height = 0.01, width = .1, alpha=my_alpha)+
  ylab('Creatinine (umol/L)')+xlab('Weight (kg)')+
  geom_hline(yintercept = 265)+
  annotate("text",
           x = min(sm_data_analysis$Weight_kg, na.rm = TRUE),  # left side
           y = 265,
           label = "265 umol/L",
           vjust = -0.5,       # move text slightly above the line
           hjust = 0,
           size = 5)+
  scale_x_continuous(transform  ='sqrt',breaks = sqrt_breaks) + 
  geom_smooth(se=SEsmooth)+
  scale_y_log10(breaks = breaks, minor_breaks = minor_breaks) +
  annotation_logticks(sides='l') +
  theme_bw(base_size = 15)+
  theme(
    legend.position = c(0.97, 0.03), 
    legend.justification = c(1, 0),
    legend.background = element_rect(fill = "white", color = "black", size = 0.5),
    legend.margin = margin(6, 6, 6, 6),  
    legend.text = element_text(size = 7),
    legend.title = element_text(size = 8))

p2 = sm_data_analysis %>%filter(!is.na(Creatinine_umol_L))%>%
  ggplot(aes(x=Age, y = Creatinine_umol_L, colour = STUDY))+
  geom_jitter(height = 0.01, width = .1, alpha=my_alpha)+
  ylab('Creatinine (umol/L)')+xlab('Age (years)')+
  geom_hline(yintercept = 265)+
  annotate("text",
           x = min(sm_data_analysis$Age, na.rm = TRUE),  # left side
           y = 265,
           label = "265 umol/L",
           vjust = -0.5,       # move text slightly above the line
           hjust = 0,
           size = 5)+
  geom_smooth(se=SEsmooth)+
  scale_y_log10(breaks = breaks, minor_breaks = minor_breaks) +
  scale_x_continuous(transform  ='sqrt',breaks = sqrt_breaks) + 
  annotation_logticks(sides='l') +
  theme_bw(base_size = 15)+theme(legend.position = 'none')

writeLines(sprintf('n=%s patients from %s studies have BUN measured',sum(!is.na(sm_data_analysis$BUN)), length(unique(sm_data_analysis$STUDY[!is.na(sm_data_analysis$BUN)]))))

p3=sm_data_analysis%>%filter(!is.na(BUN))%>%
  ggplot(aes(x=Weight_kg, y = BUN, colour = STUDY))+
  geom_jitter(height = 0.03, width = .1, alpha=my_alpha)+
  ylab('Urea nitrogen (mmol/L)')+xlab('Weight (kg)')+
  geom_hline(yintercept = 20)+
  annotate("text",
           x = min(sm_data_analysis$Weight_kg, na.rm = TRUE),  # left side
           y = 20,
           label = "20 mmol/L",
           vjust = -0.5,       # move text slightly above the line
           hjust = 0,
           size = 5)+
  scale_x_continuous(transform='sqrt',breaks = sqrt_breaks) +
  geom_smooth(se=SEsmooth)+
  scale_y_log10(breaks = breaks, minor_breaks = minor_breaks) +
  annotation_logticks(sides='l') + theme_bw(base_size = 15)+
  theme(
    legend.position = c(0.97, 0.03),        # Position the legend inside the plot (bottom-right corner)
    legend.justification = c(1, 0),       # Justify the legend to the bottom-right
    legend.background = element_rect(fill = "white", color = "black", size = 0.5),  # Optional: adds border to legend
    legend.margin = margin(6, 6, 6, 6),    # Adjust the margin around the legend if needed
    legend.text = element_text(size = 7),
    legend.title = element_text(size = 8))

p4=sm_data_analysis%>%filter(!is.na(BUN))%>%
  ggplot(aes(x=Age, y = BUN, colour = STUDY))+
  geom_jitter(height = 0.03, width = .1, alpha=my_alpha)+
  ylab('Urea nitrogen (mmol/L)')+xlab('Age (years)')+
  geom_hline(yintercept = 20)+
  annotate("text",
           x = min(sm_data_analysis$Age, na.rm = TRUE),  # left side
           y = 20,
           label = "20 mmol/L",
           vjust = -0.5,       # move text slightly above the line
           hjust = 0,
           size = 5)+
  scale_x_continuous(transform='sqrt',breaks = sqrt_breaks) +
  geom_smooth(se=SEsmooth)+
  scale_y_log10(breaks = breaks, minor_breaks = minor_breaks) +
  annotation_logticks(sides='l') + theme_bw(base_size = 15)+
  theme(legend.position='none')

grid.arrange(p1,p3,p2,p4,nrow=2)
```

Plot Creatinines by study

```{r creatinine_by_study, fig.width=12, fig.height=7}
sm_data_analysis %>% filter(!is.na(Creatinine_umol_L)) %>%
  ggplot(aes(x=Weight_kg, y = Creatinine_umol_L, colour = `Died within 28 days`))+
  geom_jitter(height = 0.01, width = .1, alpha=0.5,shape=4)+
  ylab('Creatinine (umol/L)')+xlab('Weight (kg)')+
  geom_hline(yintercept = 265)+
  geom_smooth(se=SEsmooth, aes(group=NA))+
  scale_y_log10(breaks = breaks, minor_breaks = minor_breaks) +
  scale_x_sqrt()+
  theme_bw()+ annotation_logticks(sides='l') + facet_wrap(~STUDY, nrow=2)+
   scale_colour_manual(
        name = "Died",
        values = c( "Yes" = "darkred", "No" = 'lightblue') )
```


Summary values by age group
```{r}
qqs1 = round(quantile(sm_data_analysis$Creatinine_umol_L[sm_data_analysis$Age<15 & !is.na(sm_data_analysis$Creatinine_umol_L)]))
qqs2 = round(quantile(sm_data_analysis$Creatinine_umol_L[sm_data_analysis$Age>=15 & !is.na(sm_data_analysis$Creatinine_umol_L)]))

writeLines(sprintf('The median creatinine in children under 15 years was %s (IQR: %s-%s); the median in adults was %s (IQR: %s-%s).',
                   qqs1[3],qqs1[2],qqs1[4],
                   qqs2[3],qqs2[2],qqs2[4]
))
xx = sm_data_analysis %>% filter(Age<15, !is.na(Creatinine_umol_L))
writeLines(sprintf('%s%% (%s/%s) children under 15 had a creatinine above 265umol/L',
                   round(100*mean(xx$Creatinine_umol_L>265),1),
                   sum(xx$Creatinine_umol_L>265),
                   length(xx$Creatinine_umol_L>265)))

xx = sm_data_analysis %>% filter(Age<15, !is.na(BUN))
writeLines(sprintf('%s%% (%s/%s) children under 15 had a BUN above 20mmol/L',
                   round(100*mean(xx$BUN>20),1),
                   sum(xx$BUN>20),
                   length(xx$BUN>20)))

xx = sm_data_analysis %>% filter(Age>=15, !is.na(Creatinine_umol_L))
writeLines(sprintf('%s%% (%s/%s) adults under 15 had a creatinine above 265umol/L',
                   round(100*mean(xx$Creatinine_umol_L>265),1),
                   sum(xx$Creatinine_umol_L>265),
                   length(xx$Creatinine_umol_L>265)))
xx = sm_data_analysis %>% filter(Age>=15, !is.na(BUN))
writeLines(sprintf('%s%% (%s/%s) children under 15 had a BUN above 20mmol/L',
                   round(100*mean(xx$BUN>20),1),
                   sum(xx$BUN>20),
                   length(xx$BUN>20)))

qqs1 = round(quantile(sm_data_analysis$BUN[sm_data_analysis$Age<15 & !is.na(sm_data_analysis$BUN)]),1)
qqs2 = round(quantile(sm_data_analysis$BUN[sm_data_analysis$Age>=15 & !is.na(sm_data_analysis$BUN)]),1)

writeLines(sprintf('The median BUN in children under 15 years was %s (IQR: %s-%s); the median in adults was %s (IQR: %s-%s).',
                   qqs1[3],qqs1[2],qqs1[4],
                   qqs2[3],qqs2[2],qqs2[4]
))

aggregate(Died_28D ~ (Age<15), sm_data_analysis, function(x) c(round(100*mean(x),1),sum(x), length(x)))
```


Plot BUN by study

```{r bun_by_study, fig.width=12, fig.height=7}
sm_data_analysis %>% filter(!is.na(BUN)) %>%
  ggplot(aes(x=Weight_kg, y = BUN, colour = `Died within 28 days`))+
  geom_jitter(height = 0.01, width = .1, alpha=0.5,shape=4)+
  ylab('BUN (mmol/L)')+xlab('Weight (kg)')+
  geom_hline(yintercept = 20)+
  geom_smooth(se=SEsmooth, aes(group=NA))+
  scale_y_log10(breaks = breaks, minor_breaks = minor_breaks) +
  theme_bw()+  scale_x_sqrt()+
  annotation_logticks(sides='l') + facet_wrap(~STUDY, nrow=2)+
   scale_colour_manual(
        name = "Died",
        values = c( "Yes" = "darkred", "No" = 'lightblue') )
```


BUN in studies that used the i-stat

```{r bun_istat}
xx = sm_data_analysis%>%
  filter(!is.na(BUN), STUDY %in% c('AQUAMAT','SEAQUAMAT','FEAST','Namazzi 2022', 'Conroy 2019'))

sm_data_analysis%>%
  filter(!is.na(BUN), STUDY %in% c('AQUAMAT','SEAQUAMAT','FEAST','Namazzi 2022', 'Conroy 2019'))%>%
  ggplot(aes(x=Weight_kg, y = BUN, colour = STUDY))+
  geom_jitter(height = 0.03, width = .1, alpha=my_alpha)+
  ylab('Urea nitrogen (mmol/L)')+xlab('Weight (kg)')+
  geom_hline(yintercept = 20)+
  scale_x_continuous(transform='sqrt',breaks = sqrt_breaks) +
  geom_smooth(se=SEsmooth,method = lm)+
  scale_y_log10(breaks = breaks, minor_breaks = minor_breaks) +
  annotation_logticks(sides='l') + theme_bw(base_size = 15)
```


## Hyperkalaemia

```{r bun_hyperkalaemia, fig.width=9, fig.height=7}
sm_data_analysis$STUDY=as.factor(sm_data_analysis$STUDY)
xx=sm_data_analysis %>% filter(!is.na(Potassium_mmol_L), !is.na(BUN), Potassium_mmol_L<12)
xx1 = xx %>% filter(Age<15, BUN>3, BUN<50) %>% droplevels()%>%
  mutate(HP = as.numeric(Potassium_mmol_L>8)) 

xx %>% ggplot(aes(x=BUN, y=Potassium_mmol_L, color=STUDY))+  
  scale_x_log10(breaks = breaks, minor_breaks = minor_breaks) +
  geom_point(alpha=.3)+ theme_bw(base_size = 15)+
  ggtitle(paste('n=',nrow(xx)))+
  xlab('Blood urea nitrogen (mmol/L)')+
  ylab('Potassium (mmol/L)')+geom_smooth(se = F)

writeLines(sprintf('In a combined database of %s children <15 years with severe malaria hypokalaemia (K+<3.5 mmol/L) was found on admission in %s%%, and high blood potassium level (K+>6.5 mmol/L) were found in %s%%. Very high values (>9mmol/L, %s%%) were unrelated to acidosis or renal impairment and were most likely spurious resulting from blood sample haemolysis). Otherwise hyperkalaemia correlated with metabolic acidosis and elevated blood urea.',
                   nrow(xx1), 
                   round(100*mean(xx1$Potassium_mmol_L<3.5),1),
                   round(100*mean(xx1$Potassium_mmol_L>6.5),1),
                   round(100*mean(xx1$Potassium_mmol_L>9),1)))
mod = mgcv::gam(as.numeric(Potassium_mmol_L>8) ~ s(log10(BUN), k=5) + STUDY,
                data = xx1, family = 'binomial')
summary(mod)

table(xx1$STUDY)
xx %>% ggplot(aes(x=BUN, y=Potassium_mmol_L, color=Age_category))+  
  scale_x_log10(breaks = breaks, minor_breaks = minor_breaks) +
  geom_point(alpha=.3)+ theme_bw(base_size = 15)+
  labs(colour="Age category")+ggtitle(paste('n=',nrow(xx)))+
  xlab('Blood urea nitrogen (mmol/L)')+
  ylab('Potassium (mmol/L)')+geom_smooth(se = F)+
  scale_color_manual(
    values = c(
      "≤2"     = "lightblue",
      "(2,5]"  = "lightgreen",
      "(5,15]" = "purple",
      ">15"    = "darkblue"   # adults
    ),
    breaks = levels(xx$Age_category),
    drop = FALSE
  ) +
  guides(colour = guide_legend(override.aes = list(alpha = 1)))



xx=sm_data_analysis %>% filter(!is.na(`Base Excess_mmol_L`), !is.na(BUN)) 
table(xx$STUDY)
xx%>%ggplot(aes(x=BUN, y=`Base Excess_mmol_L`, color=Age_category))+  
  scale_x_log10(breaks = breaks, minor_breaks = minor_breaks) +
  geom_point(alpha=.3)+ theme_bw(base_size = 15)+
  labs(colour="Age category")+ggtitle(paste('n=',nrow(xx)))+
  xlab('Blood urea nitrogen (mmol/L)')+
  ylab('Base excess (mmol/L)')+geom_smooth(se = F)

xx=sm_data_analysis %>% filter(!is.na(Potassium_mmol_L),Potassium_mmol_L<12,!is.na(Lactate)) 
table(xx$STUDY)
xx %>% ggplot(aes(x=Lactate, y=Potassium_mmol_L, color=Age_category))+  
  geom_point(alpha=.3)+ theme_bw(base_size = 15)+
  labs(colour="Age category")+ggtitle(paste('n=',nrow(xx)))+
  xlab('Lactate (mmol/L)')+
  ylab('Potassium (mmol/L)')+geom_smooth(se = F)

xx =sm_data_analysis %>% filter(!is.na(Potassium_mmol_L), Potassium_mmol_L<12, !is.na(`Base Excess_mmol_L`), `Base Excess_mmol_L`<10) 
table(xx$STUDY)
xx %>% ggplot(aes(x=`Base Excess_mmol_L`, y=Potassium_mmol_L, color=Age_category))+  
  geom_point(alpha=.3)+ theme_bw(base_size = 15)+
  labs(colour="Age category")+ggtitle(paste('n=',nrow(xx)))+
  xlab('Base excess (mmol/L)')+
  ylab('Potassium (mmol/L)')+geom_smooth(se = F)

xx =sm_data_analysis %>% filter(!is.na(Lactate), !is.na(`Base Excess_mmol_L`), `Base Excess_mmol_L`<10) 
table(xx$STUDY)
xx %>% ggplot(aes(x=`Base Excess_mmol_L`, y=Lactate, color=Age_category))+  
  geom_point(alpha=.3)+ theme_bw(base_size = 15)+
  labs(colour="Age category")+ggtitle(paste('n=',nrow(xx)))+
  xlab('Base excess (mmol/L)')+
  ylab('Lactate (mmol/L)')+geom_smooth(se = F)

xx = sm_data_analysis %>% filter(!is.na(Sodium_mmol_L), !is.na(Potassium_mmol_L), Potassium_mmol_L<12, Sodium_mmol_L>100) 
table(xx$STUDY)
xx %>% ggplot(aes(x=Sodium_mmol_L, y=Potassium_mmol_L, color=Age_category))+  
  geom_point()+ theme_bw(base_size = 15)+
  labs(colour="Age category")+ggtitle(paste('n=',nrow(xx)))+
  xlab('Sodium (mmol/L)')+
  ylab('Potassium (mmol/L)')+geom_smooth(se = F)
```



## Mortality

### Bin BUN and Creatinine

```{r}
# Bin BUN & Creatinine into reasonable groups 
bun_cuts = c(.5, 5, 10, 20, 200)
creat_cuts = c(5,65, 130, 265, 2000)
sm_data_analysis = sm_data_analysis %>%
  mutate(BUN_groups = cut(BUN, breaks = bun_cuts,include.lowest = T),
         Creat_groups = cut(Creatinine_umol_L, breaks = creat_cuts,include.lowest = T))  
levels(sm_data_analysis$BUN_groups)=c("<5","(5,10]","(10,20]",">20")
levels(sm_data_analysis$Creat_groups)=c("<65","(65,130]","(130,265]",">265")

print(table(Age=sm_data_analysis$Age_Categories3, Creatinine=sm_data_analysis$Creat_groups))
print(table(Age=sm_data_analysis$Age_Categories3, Creatinine=sm_data_analysis$Creatinine_umol_L>265))

print(table(Age=sm_data_analysis$Age_Categories3, Creatinine_High=sm_data_analysis$Creat_groups=='>265'))


print(table(Age=sm_data_analysis$Age_Categories3, BUN=sm_data_analysis$BUN_groups))
print(table(Age=sm_data_analysis$Age_Categories3, Creatinine_High=sm_data_analysis$BUN_groups=='>20'))

table(sm_data_analysis$Age_Categories3, sm_data_analysis$`Died within 28 days`)
```


### Non parametric


Using measured BUN data

```{r bun_groups_mortality}
sm_dat_bun = sm_data_analysis %>% filter(BUN_ANALYSIS) 

# Summarize by BUN quantile and Coma
summary_df <- sm_dat_bun %>% filter(!is.na(BUN)) %>%
  group_by(Coma, BUN_groups, Age_Categories3) %>%
  summarise(
    mortality = mean(Died),
    n = n(),
    se = sqrt(mortality * (1 - mortality) / n),
    lower = 100*(mortality - 1.96 * se),
    upper = 100*(mortality + 1.96 * se),
    mortality = 100*mortality,
    .groups = "drop"
  )

# Plot
p1=summary_df %>% ggplot(aes(x = BUN_groups, y = mortality, group = Coma, colour = Coma)) +
  geom_point(aes(size = n), position = position_dodge(width = 0.4)) +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2,
                position = position_dodge(width = 0.4)) +
  scale_size(trans = "sqrt",  # visual transformation
             range = c(1, 8),
             breaks = c(100, 500, 2000),  # values of n you want to show
             labels = c("100", "500", "2000")) + 
  scale_colour_manual(
    name = "Coma",
    values = c("No" = "grey", "Yes" = "pink") 
  )+labs(
    x = "BUN (mmol/L)",
    y = "Mortality (%)",
    size = "n") + 
  geom_hline(yintercept = 100*mortality_threshold)+
  theme_bw(base_size = 16)+facet_wrap(vars(Age_Categories3))
```



using the measured creatinine

```{r creat_groups_mortality}
sm_dat_creat = sm_data_analysis %>% 
  filter(CREAT_ANALYSIS)

# Summarize by Creatinine quantile and Coma
summary_df <- sm_dat_creat %>% filter(!is.na(Creatinine_umol_L)) %>%
  group_by(Creat_groups, Coma, Age_Categories3) %>%
  summarise(
    mortality = mean(Died),
    deaths = sum(Died),
    n = n(),
    se = sqrt(mortality * (1 - mortality) / n),
    lower = 100*(mortality - 1.96 * se),
    upper = 100*(mortality + 1.96 * se),
    mortality = 100*mortality,
    .groups = "drop"
  ) %>% filter(n>20)

# Plot
p2=summary_df %>% ggplot(aes(x = Creat_groups, y = mortality, group = Coma, colour = Coma)) +
  geom_point(aes(size = n), position = position_dodge(width = 0.4)) +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2,
                position = position_dodge(width = 0.4)) +
  scale_size(trans = "sqrt",  # visual transformation
             range = c(1, 8),
             breaks = c(100, 500, 2000),  # values of n you want to show
             labels = c("100", "500", "2000")) +
  scale_colour_manual(
    name = "Coma",
    values = c("No" = "grey", "Yes" = "pink") 
  )+
  labs(
    x = "Creatinine (umol/L)",
    y = "Mortality (%)",
    size = "n") + geom_hline(yintercept = 100*mortality_threshold)+
  theme_bw(base_size = 16)+facet_wrap(vars(Age_Categories3))
sum(summary_df$n)
```





```{r non_para_mortality, fig.width=12, fig.height=8}
grid.arrange(p1,p2)
```

#### Individual studies

```{r indiv_studies, fig.width=12, fig.height=8}
sm_dat_creat %>%
  group_by(STUDY) %>%
  mutate(STUDY = paste0(STUDY, " (n = ", n(), ")")) %>%
  ggplot(aes(x=Creatinine_umol_L, y = Died_28D))+
  geom_point()+
  scale_x_log10(minor_breaks=minor_breaks, breaks=breaks)+theme_bw()+
  geom_hline(yintercept = mortality_threshold)+ylab('Proportion dead by day 28')+
  xlab('Creatinine (umol/L)')+ geom_vline(xintercept = 265)+
  geom_smooth(method='gam',method.args = list(family='binomial'))+
  facet_wrap(~STUDY, nrow=2)

sm_dat_bun %>%
  group_by(STUDY) %>%
  mutate(STUDY = paste0(STUDY, " (n = ", n(), ")")) %>%
  ggplot(aes(x=BUN, y = Died_28D))+
  geom_point()+
  scale_x_log10(minor_breaks=minor_breaks, breaks=breaks)+theme_bw()+
  geom_hline(yintercept = mortality_threshold)+ylab('Proportion dead by day 28')+
  xlab('Urea Nitrogen (mmol/L)')+ geom_vline(xintercept = 20)+
  geom_smooth(method='gam',method.args = list(family='binomial'))+
  facet_wrap(~STUDY,nrow=3)

#Fits by age category
sm_dat_bun %>% filter(Coma=='No', STUDY!='TRACT')%>%
  ggplot(aes(x=BUN, y = Died_28D))+
  geom_point()+
  scale_x_log10(minor_breaks=minor_breaks, breaks=breaks)+theme_bw()+
  geom_hline(yintercept = mortality_threshold)+ylab('Proportion dead by day 28')+
  xlab('Urea Nitrogen (mmol/L)')+ geom_vline(xintercept = 20)+
  geom_smooth(method='gam',method.args = list(family='binomial'))+
  facet_wrap(~Age_category)
```

## Proportion base excess explained

```{r}
sm_data_analysis$BaseExcess=sm_data_analysis$`Base Excess_mmol_L`
mod_BE = mgcv::gam(BaseExcess ~ s(Bicarbonate_mEq_L), data=sm_data_analysis)

sm_data_acidosis = sm_data_analysis %>%
  filter(!is.na(BaseExcess) | !is.na(Bicarbonate_mEq_L),
         !is.na(Creatinine_umol_L),
         !is.na(Lactate), 
         !is.na(Hb)) %>%
  mutate(
    BaseExcess = ifelse(!is.na(BaseExcess)&BaseExcess>10,NA, BaseExcess),
    BaseExcess_pred = ifelse(!is.na(Bicarbonate_mEq_L),
                             predict(mod_BE, newdata = data.frame(Bicarbonate_mEq_L=Bicarbonate_mEq_L)),
                             NA),
    Q = 0.0270*Age + 0.2329,
    bSrc_adults = 88.4*((140-Age)*Weight_kg)/(100*72),
    bSrc_children = (107.3/120)*Q*88.4,
    bSrc = ifelse(Age<15, bSrc_children, bSrc_adults),
    Creatinine_FC_log2 = log2(Creatinine_umol_L/bSrc))
nrow(sm_data_acidosis)

mod1=lme4::lmer(BaseExcess ~ Creatinine_FC_log2 * Lactate + (Hb<5) + Age_category + (1|STUDY), data= sm_data_acidosis)
summary(mod1)

p1=sm_data_acidosis %>% ggplot(aes(x=Creatinine_FC_log2, y=BaseExcess, colour = Hb<5))+
  geom_point(alpha=.6)+theme_bw()+geom_smooth(method=lm,se = F)+
  xlab('Creatinine fold change from baseline')+ylab('Base Excess (mmol/L)')+
  theme(legend.position = c(.8,.8))

p2=sm_data_acidosis %>% ggplot(aes(x=Creatinine_FC_log2, y=Lactate, colour = Hb<5))+
  geom_point(alpha=.6)+theme_bw()+geom_smooth(method=lm,se = F)+
  xlab('Creatinine fold change from baseline')+ylab('Lactate (mmol/L)')+
  theme(legend.position = 'none')

p3=sm_data_acidosis %>% ggplot(aes(x=Lactate, y=BaseExcess, colour = Hb<5))+
  geom_point(alpha=.6)+theme_bw()+geom_smooth(method=lm,se = F)+
  xlab('Lactate (mmol/L)')+ylab('Base Excess (mmol/L)')+
  theme(legend.position = 'none')
grid.arrange(p1,p2,p3)
```


## BUN/Creatinine vs Potassium 

```{r bun_Cr_potassium, fig.width=10, fig.height=8}
xx = sm_data_analysis %>% filter(Potassium_mmol_L<=10, !is.na(Potassium_mmol_L)) 
table(xx$Potassium_mmol_L>6.5, xx$Age<15)
aggregate((Potassium_mmol_L>6.5) ~ Age_category, data = xx, FUN = mean)

xx %>%
  ggplot(aes(x=Age, y = Potassium_mmol_L))+
  geom_point(alpha=0.3, shape=4)+
  ylab('Potassium (mmol/L)')+xlab('Age (years)')+
  scale_x_sqrt()+geom_vline(xintercept = c(2,5))+
  theme_bw(base_size = 20)+geom_hline(yintercept = c(3.5, 6.5),color='red')+
  geom_smooth(se = F)

xx = xx%>% filter(!is.na(BUN))
p1= xx %>%
  ggplot(aes(x=BUN, y = Potassium_mmol_L))+
  geom_point(alpha=0.3, shape=4)+
  ylab('Potassium (mmol/L)')+xlab('BUN (mmol/L)')+
  scale_x_log10(breaks=breaks, minor_breaks=minor_breaks)+
  theme_bw(base_size = 16)+geom_hline(yintercept = c(3.5, 6.5),color='red')+
  geom_smooth(se = F)

xx = sm_data_analysis %>% filter(Potassium_mmol_L<=10, !is.na(Potassium_mmol_L), !is.na(Creatinine_umol_L)) 
p2=sm_data_analysis %>% filter(Potassium_mmol_L<=10) %>%
  ggplot(aes(x=Creatinine_umol_L, y = Potassium_mmol_L))+
  geom_point(alpha=0.3, shape=4)+
  ylab('Potassium (mmol/L)')+xlab('Creatinine (umol/L)')+
  scale_x_log10(breaks=breaks, minor_breaks=minor_breaks)+
  theme_bw(base_size = 16)+geom_hline(yintercept = c(3.5, 6.5),color='red')+
  geom_smooth(se = F)
grid.arrange(p1,p2)

aggregate((Potassium_mmol_L>=7.5) ~ Age_category + (BUN>10), data = sm_data_analysis, mean)


p0= xx %>%
  ggplot(aes(x=Age, y = Potassium_mmol_L))+
  geom_point(alpha=0.3, shape=4)+
  ylab('Potassium (mmol/L)')+xlab('Age (years)')+
  scale_x_sqrt()+
  theme_bw(base_size = 18)+geom_hline(yintercept = c(3.5, 6.5),color='red')+
  geom_smooth(se = F)
p1= xx %>%
  ggplot(aes(x=BUN, y = Potassium_mmol_L))+
  geom_point(alpha=0.3, shape=4)+
  ylab('Potassium (mmol/L)')+xlab('BUN (mmol/L)')+
  scale_x_log10(breaks=breaks, minor_breaks=minor_breaks)+
  theme_bw(base_size = 18)+geom_hline(yintercept = c(3.5, 6.5),color='red')+
  geom_smooth(se = F)
p2= xx %>%
  ggplot(aes(x=Bicarbonate_imputed, y = Potassium_mmol_L))+
  geom_point(alpha=0.3, shape=4)+
  xlab('Bicarbonate (mEq/L)')+ylab('Potassium (mmol/L)')+
  theme_bw(base_size = 18)+geom_hline(yintercept = c(3.5, 6.5),color='red')+
  geom_smooth(se = F)
p3= xx %>%
  ggplot(aes(x=Lactate_imputed, y = Potassium_mmol_L))+
  geom_point(alpha=0.3, shape=4)+
  xlab('Lactate (mmol/L)')+ylab('Potassium (mmol/L)')+
  theme_bw(base_size = 18)+geom_hline(yintercept = c(3.5, 6.5),color='red')+
  geom_smooth(se = F)
grid.arrange(p0,p1,p2,p3)
```


